### PR TITLE
split steps.py and merge nmcli and nmtui steps

### PR DESCRIPTION
**Pull request by fpokryvk**
split nmcli steps.py into following files (for better readability):
 * bond_team_bridge - not so much of them to create separate files
 * commands - various commands like Execute, Ping, Wait...
 * connection - management of connections
 * device - management of various devices (nmcli device)
 * editor - editor related steps
 * files - file management steps
 * prepare - (long) prepare steps (usually firsts steps in scenarios)
           - maybe it would be better to convert these steps to prepare
scripts
 * service - controlling state of NM (Start, Stop, Kill...)
 * vpn - vpn related steps

link all nmcli steps to nmtui steps to prevent duplicate definitions of steps

increase the stability of step 'Check bond "{bond}" link state is "{state}" ' step by adding a number of retries and increase time performance by decreasing timeout between retries

@Build:nm-1-16

### CODE REVIEW

**Comment by vbenes** [comment]
the first failure is a bug https://bugzilla.redhat.com/show_bug.cgi?id=1684389
and the second one is a missing fix for bond_send_correct_arp
retesting for 1.16

**Comment by vbenes** [comment]
rebuild

**Comment by fpokryvk** [comment]
Now there is something with teamd in default_route_for_vlan_over_team (from NM log):

Using team device "team7".
Using PID file "/var/run/teamd/team7.pid"
This program is not intended to be run as root.
Added loop callback: daemon, 0x560473cbfce0
Added loop callback: libteam_events, 0x560473cbfce0
Added loop callback: workq, 0x560473cbfce0
Failed to get team runner name from config.
Using default team runner "roundrobin".
Failed to set team mode "roundrobin".
Failed to init runner.
Removed loop callback: workq, 0x560473cbfce0
Removed loop callback: libteam_events, 0x560473cbfce0
Removed loop callback: daemon, 0x560473cbfce0
teamd_init() failed.
Failed: Cannot allocate memory

The same error was in the first run, so it is seems reproducible.
Also, team7 interface stays after failed test, it is cleaned up by the next step.
But, this does not seem to be related to steps.py split, since only basic steps are being used before fail (add connection, bring up connection), and this steps are used in hundreds of other tests, which are passing.

**Comment by vbenes** [comment]
regarding default_route_for_vlan_over_team:
it's https://bugzilla.redhat.com/show_bug.cgi?id=1680655

so expected, could you rerun with 7.6 1.10 and 1.12? We have to be sure it's working there too.

**Comment by vbenes** [comment]
everything running well on 7.6 stock and 1.10

**Pull request merged**
