### PR TITLE
Make the script more robust

### PR DESCRIPTION
**Pull request by Pavche**
1. Check for number of parameters.
2. Make runnable for users with root priv. Remove "sudo" keywords from the script.
3. Replace all occurrences of /etc/racoon with $RACOON_DIR

### CODE REVIEW

**Comment by vhumpa** [comment]
Can one of the admins verify this patch?

**Comment by vhumpa** [comment]
add to whitelist

**Comment by vhumpa** [comment]
rebuild

**Comment by vbenes** [comment]
rebuild

**Pull request merged**
