### PR TITLE
dns: add DNS tests for systemd-resolved and dnsmasq

### PR DESCRIPTION
**Pull request by bengal**
https://bugzilla.gnome.org/show_bug.cgi?id=746422
https://bugzilla.redhat.com/show_bug.cgi?id=1512966

@Build:master

### CODE REVIEW

**Comment by vhumpa** [comment]
rebuild

**Comment by vhumpa** [comment]
rebuild

**Comment by vbenes** [comment]
rebuild

**Comment by vbenes** [comment]
rebuild

**Pull request merged**
