### PR TITLE
Add new test scenarios for ModemManager

### PR DESCRIPTION
**Pull request by Pavche**
Implement tests for two useful functions of ModemManager:
1. List available modems via mmcli
2. Increase verbosity level to DEBUG in the system journal

### CODE REVIEW

**Comment by Pavche** [comment]
Successful test: https://beaker.engineering.redhat.com/jobs/2171577

**Comment by Pavche** [comment]
Tests are only for ModemManager and are not related to NetworkManager.

**Comment by thom311** [comment]
for MM we don't have an extensive test suite. Also, the NM test suit has tests that uses (indirectly) MM.

I think it would make sense to have these tests here.

**Comment by vbenes** [comment]
we need to create separated MM repo where such tests belong

**Comment by thom311** [comment]
Ok

**Pull request closed without merging**
